import { 
    LayoutGrid, 
    Users, 
    Building2, 
    Activity, 
    Calendar, 
    CheckSquare, 
    FileText,
    Target, 
    FileSpreadsheet, 
    ShoppingBag, 
    Truck, 
    Receipt, 
    CreditCard, 
    Wallet,
    Hammer, 
    ClipboardList, 
    Layers, 
    GitFork, 
    Cpu, 
    ShieldCheck,
    Warehouse as WarehouseIcon, 
    MapPin, 
    Package, 
    ArrowDownToLine, 
    ArrowUpFromLine, 
    Repeat, 
    Sliders, 
    ClipboardCheck,
    FilePlus, 
    ShoppingCart, 
    Store, 
    DollarSign, 
    Landmark, 
    Scale,
    PieChart, 
    BarChart3, 
    TrendingUp, 
    Download,
    PackageSearch, 
    FolderTree, 
    Tag, 
    Box, 
    Percent, 
    Ruler, 
    Coins,
    UserCheck, 
    Shield, 
    Key, 
    Building, 
    Briefcase, 
    GitBranch, 
    Bell, 
    History, 
    Globe, 
    Settings,
    LucideIcon
} from 'lucide-react';

export interface NavSubItem {
    title: string;
    href: string;
    icon: LucideIcon;
    permission?: string;
    plannedSprint?: string;
    comingSoon?: boolean;
    description?: string;
}

export interface NavGroup {
    title: string;
    icon: LucideIcon;
    items: NavSubItem[];
}

export const navigationConfig: NavGroup[] = [
    {
        title: 'Dashboard',
        icon: LayoutGrid,
        items: [
            {
                title: 'Dashboard',
                href: '/dashboard',
                icon: LayoutGrid,
                permission: 'view-dashboard',
            },
        ],
    },
    {
        title: 'CRM',
        icon: Users,
        items: [
            {
                title: 'Leads',
                href: '/leads',
                icon: Users,
                permission: 'view-leads',
            },
            {
                title: 'Customers',
                href: '/customers',
                icon: Building2,
                permission: 'view-customers',
            },
            {
                title: 'Activities',
                href: '/crm/activities',
                icon: Activity,
                permission: 'view-activities',
                description: 'Record sales calls, meetings, and follow-up activities.',
            },
            {
                title: 'Calendar',
                href: '/crm/calendar',
                icon: Calendar,
                permission: 'view-calendar',
                description: 'Interactive sales calendar and appointment scheduler.',
            },
            {
                title: 'Tasks',
                href: '/crm/tasks',
                icon: CheckSquare,
                permission: 'view-tasks',
                description: 'Manage individual and team sales tasks.',
            },
            {
                title: 'Documents',
                href: '/crm/documents',
                icon: FileText,
                permission: 'view-documents',
                description: 'Centralized customer document and contract repository.',
            },
        ],
    },
    {
        title: 'Sales',
        icon: ShoppingBag,
        items: [
            {
                title: 'Opportunities',
                href: '/opportunities',
                icon: Target,
                permission: 'view-opportunities',
            },
            {
                title: 'Quotations',
                href: '/quotations',
                icon: FileSpreadsheet,
                permission: 'view-quotations',
            },
            {
                title: 'Sales Orders',
                href: '/sales-orders',
                icon: ShoppingBag,
                permission: 'view-sales-orders',
            },
            {
                title: 'Delivery Orders',
                href: '/delivery-orders',
                icon: Truck,
                permission: 'view-delivery-orders',
            },
            {
                title: 'Invoices',
                href: '/invoices',
                icon: Receipt,
                permission: 'view-invoices',
            },
            {
                title: 'Payments',
                href: '/payments',
                icon: CreditCard,
                permission: 'view-payments',
            },
            {
                title: 'Receivables',
                href: '/receivables',
                icon: Wallet,
                permission: 'view-receivables',
            },
        ],
    },
    {
        title: 'Production',
        icon: Hammer,
        items: [
            {
                title: 'Production Orders',
                href: '/production-orders',
                icon: Hammer,
                permission: 'view-production-orders',
            },
            {
                title: 'Work Orders',
                href: '/production/work-orders',
                icon: ClipboardList,
                permission: 'view-work-orders',
                comingSoon: true,
                plannedSprint: 'Sprint 26',
                description: 'Factory floor work order execution tickets.',
            },
            {
                title: 'Bill Of Materials',
                href: '/production/bom',
                icon: Layers,
                permission: 'view-bom',
                comingSoon: true,
                plannedSprint: 'Sprint 26',
                description: 'Configure furniture raw material recipes.',
            },
            {
                title: 'Routing',
                href: '/production/routing',
                icon: GitFork,
                permission: 'view-routing',
                comingSoon: true,
                plannedSprint: 'Sprint 27',
                description: 'Configure machinery station routing sequences.',
            },
            {
                title: 'Work Centers',
                href: '/production/work-centers',
                icon: Cpu,
                permission: 'view-work-centers',
                comingSoon: true,
                plannedSprint: 'Sprint 27',
                description: 'Monitor factory machine stations and capacity.',
            },
            {
                title: 'Quality Control',
                href: '/production/qc',
                icon: ShieldCheck,
                permission: 'view-qc',
                comingSoon: true,
                plannedSprint: 'Sprint 28',
                description: 'Quality assurance and product inspection sheets.',
            },
        ],
    },
    {
        title: 'Warehouse',
        icon: WarehouseIcon,
        items: [
            {
                title: 'Warehouses',
                href: '/warehouses',
                icon: WarehouseIcon,
                permission: 'view-warehouses',
            },
            {
                title: 'Storage Locations',
                href: '/warehouse/locations',
                icon: MapPin,
                permission: 'view-storage-locations',
                comingSoon: true,
                plannedSprint: 'Sprint 29',
                description: 'Map physical warehouse plants, racks, and bins.',
            },
            {
                title: 'Inventory',
                href: '/inventory',
                icon: Package,
                permission: 'view-inventory',
            },
            {
                title: 'Goods Receipt',
                href: '/goods-receipts',
                icon: ArrowDownToLine,
                permission: 'view-goods-receipts',
            },
            {
                title: 'Goods Issue',
                href: '/goods-issues',
                icon: ArrowUpFromLine,
                permission: 'view-goods-issues',
            },
            {
                title: 'Stock Transfer',
                href: '/warehouse/stock-transfer',
                icon: Repeat,
                permission: 'transfer-stock',
                comingSoon: true,
                plannedSprint: 'Sprint 30',
                description: 'Inter-warehouse inventory stock movement.',
            },
            {
                title: 'Stock Adjustment',
                href: '/stock-adjustments',
                icon: Sliders,
                permission: 'adjust-inventory',
            },
            {
                title: 'Stock Opname',
                href: '/warehouse/stock-opname',
                icon: ClipboardCheck,
                permission: 'opname-stock',
                comingSoon: true,
                plannedSprint: 'Sprint 31',
                description: 'Physical inventory audit and variance reconciler.',
            },
        ],
    },
    {
        title: 'Purchasing',
        icon: ShoppingCart,
        items: [
            {
                title: 'Purchase Requests',
                href: '/purchasing/requests',
                icon: FilePlus,
                permission: 'view-purchase-requests',
                comingSoon: true,
                plannedSprint: 'Sprint 32',
                description: 'Internal material purchase requisitions.',
            },
            {
                title: 'Purchase Orders',
                href: '/purchasing/orders',
                icon: ShoppingCart,
                permission: 'view-purchase-orders',
                comingSoon: true,
                plannedSprint: 'Sprint 32',
                description: 'Issue procurement contracts to suppliers.',
            },
            {
                title: 'Suppliers',
                href: '/purchasing/suppliers',
                icon: Store,
                permission: 'view-suppliers',
                comingSoon: true,
                plannedSprint: 'Sprint 33',
                description: 'Vendor directory and supplier master data.',
            },
            {
                title: 'Supplier Receipts',
                href: '/purchasing/receipts',
                icon: Receipt,
                permission: 'view-supplier-receipts',
                comingSoon: true,
                plannedSprint: 'Sprint 33',
                description: 'Log supplier bills and accounts payable notes.',
            },
        ],
    },
    {
        title: 'Finance',
        icon: Landmark,
        items: [
            {
                title: 'Invoices',
                href: '/invoices',
                icon: Receipt,
                permission: 'view-invoices',
            },
            {
                title: 'Payments',
                href: '/payments',
                icon: CreditCard,
                permission: 'view-payments',
            },
            {
                title: 'Receivables',
                href: '/receivables',
                icon: Wallet,
                permission: 'view-receivables',
            },
            {
                title: 'Payables',
                href: '/finance/payables',
                icon: DollarSign,
                permission: 'view-payables',
                comingSoon: true,
                plannedSprint: 'Sprint 34',
                description: 'Vendor accounts payable aging and payment schedules.',
            },
            {
                title: 'Cash & Bank',
                href: '/finance/cash-bank',
                icon: Landmark,
                permission: 'view-cash-bank',
                comingSoon: true,
                plannedSprint: 'Sprint 35',
                description: 'Manage bank accounts and cash flow balances.',
            },
            {
                title: 'Reconciliation',
                href: '/finance/reconciliation',
                icon: Scale,
                permission: 'view-reconciliation',
                comingSoon: true,
                plannedSprint: 'Sprint 35',
                description: 'Bank statement matching and reconciliation.',
            },
        ],
    },
    {
        title: 'Reports',
        icon: BarChart3,
        items: [
            {
                title: 'Analytics Dashboard',
                href: '/reports/analytics',
                icon: PieChart,
                permission: 'view-reports',
                comingSoon: true,
                plannedSprint: 'Sprint 36',
                description: 'Executive BI dashboards and cross-module metrics.',
            },
            {
                title: 'Sales Report',
                href: '/reports/sales',
                icon: BarChart3,
                permission: 'view-reports',
                comingSoon: true,
                plannedSprint: 'Sprint 36',
                description: 'Comprehensive commercial sales performance report.',
            },
            {
                title: 'Customer Report',
                href: '/reports/customers',
                icon: Users,
                permission: 'view-reports',
                comingSoon: true,
                plannedSprint: 'Sprint 37',
                description: 'Customer lifetime value and acquisition analytics.',
            },
            {
                title: 'Production Report',
                href: '/reports/production',
                icon: Hammer,
                permission: 'view-reports',
                comingSoon: true,
                plannedSprint: 'Sprint 37',
                description: 'OEE efficiency and factory output analytics.',
            },
            {
                title: 'Inventory Report',
                href: '/reports/inventory',
                icon: Package,
                permission: 'view-reports',
                comingSoon: true,
                plannedSprint: 'Sprint 38',
                description: 'Inventory turnover ratio and dead stock analysis.',
            },
            {
                title: 'Finance Report',
                href: '/reports/finance',
                icon: Landmark,
                permission: 'view-reports',
                comingSoon: true,
                plannedSprint: 'Sprint 38',
                description: 'Trial balance, GL ledger summary, and tax reports.',
            },
            {
                title: 'Profit & Loss',
                href: '/reports/pnl',
                icon: TrendingUp,
                permission: 'view-reports',
                comingSoon: true,
                plannedSprint: 'Sprint 38',
                description: 'Income statement and corporate P&L breakdown.',
            },
            {
                title: 'Export Data',
                href: '/reports/export',
                icon: Download,
                permission: 'export-data',
                comingSoon: true,
                plannedSprint: 'Sprint 38',
                description: 'Bulk CSV / Excel data exporter for ERP data.',
            },
        ],
    },
    {
        title: 'Master Data',
        icon: FolderTree,
        items: [
            {
                title: 'Products',
                href: '/master/products',
                icon: PackageSearch,
                permission: 'view-products',
            },
            {
                title: 'Categories',
                href: '/master/categories',
                icon: FolderTree,
                permission: 'manage-master-data',
                comingSoon: true,
                plannedSprint: 'Sprint 28',
                description: 'Product category taxonomy and hierarchy.',
            },
            {
                title: 'Brands',
                href: '/master/brands',
                icon: Tag,
                permission: 'manage-master-data',
                comingSoon: true,
                plannedSprint: 'Sprint 28',
                description: 'Manage furniture product brand lines.',
            },
            {
                title: 'Materials',
                href: '/master/materials',
                icon: Box,
                permission: 'manage-master-data',
                comingSoon: true,
                plannedSprint: 'Sprint 28',
                description: 'Raw material grade and veneer catalog.',
            },
            {
                title: 'Suppliers',
                href: '/purchasing/suppliers',
                icon: Store,
                permission: 'manage-master-data',
                comingSoon: true,
                plannedSprint: 'Sprint 33',
                description: 'Vendor master data and supplier accounts.',
            },
            {
                title: 'Taxes',
                href: '/master/taxes',
                icon: Percent,
                permission: 'manage-master-data',
                comingSoon: true,
                plannedSprint: 'Sprint 34',
                description: 'Configure PPN, PPh, and tax rate codes.',
            },
            {
                title: 'Units',
                href: '/master/units',
                icon: Ruler,
                permission: 'manage-master-data',
                comingSoon: true,
                plannedSprint: 'Sprint 28',
                description: 'Units of measurement (Pcs, Set, Meter, Kg).',
            },
            {
                title: 'Currencies',
                href: '/master/currencies',
                icon: Coins,
                permission: 'manage-master-data',
                comingSoon: true,
                plannedSprint: 'Sprint 34',
                description: 'Multi-currency exchange rate tables.',
            },
        ],
    },
    {
        title: 'System',
        icon: Settings,
        items: [
            {
                title: 'Users',
                href: '/users',
                icon: UserCheck,
                permission: 'manage-users',
            },
            {
                title: 'Roles',
                href: '/system/roles',
                icon: Shield,
                permission: 'manage-roles',
                comingSoon: true,
                plannedSprint: 'Sprint 39',
                description: 'Configure RBAC security roles.',
            },
            {
                title: 'Permissions',
                href: '/system/permissions',
                icon: Key,
                permission: 'manage-permissions',
                comingSoon: true,
                plannedSprint: 'Sprint 39',
                description: 'Granular policy permission definitions.',
            },
            {
                title: 'Tenants',
                href: '/system/tenants',
                icon: Building,
                permission: 'manage-tenants',
                comingSoon: true,
                plannedSprint: 'Sprint 40',
                description: 'Multi-tenant SaaS organization management.',
            },
            {
                title: 'Companies',
                href: '/system/companies',
                icon: Briefcase,
                permission: 'manage-companies',
                comingSoon: true,
                plannedSprint: 'Sprint 38',
                description: 'Multi-company legal entity setup.',
            },
            {
                title: 'Branches',
                href: '/system/branches',
                icon: GitBranch,
                permission: 'manage-branches',
                comingSoon: true,
                plannedSprint: 'Sprint 38',
                description: 'Branch plant and store office setup.',
            },
            {
                title: 'Notifications',
                href: '/system/notifications',
                icon: Bell,
                permission: 'view-notifications',
                comingSoon: true,
                plannedSprint: 'Sprint 39',
                description: 'System alert triggers and notification preferences.',
            },
            {
                title: 'Audit Logs',
                href: '/system/audit-logs',
                icon: History,
                permission: 'view-audit-logs',
                comingSoon: true,
                plannedSprint: 'Sprint 39',
                description: 'Enterprise event audit trail and transactional outbox.',
            },
            {
                title: 'Integrations',
                href: '/finance/integration',
                icon: Globe,
                permission: 'manage-integrations',
            },
            {
                title: 'Settings',
                href: '/settings/profile',
                icon: Settings,
                permission: 'view-settings',
            },
        ],
    },
];

// Backwards compatibility export
export const mainNavItems = navigationConfig.flatMap(group => 
    group.items.map(item => ({
        title: item.title,
        href: item.href,
        icon: item.icon,
        requiredPermission: item.permission
    }))
);
